#ifndef COMMUNAL_H
#define COMMUNAL_H

#include <QMainWindow>
#include <QMenuBar>
#include <QAction>
#include <QMenu>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QTextEdit>
#include <QFileDialog>
#include <QMessageBox>
#include <QFile>
#include <QTextStream>
#include <QFont>
#include <QFontDialog>
#include <QSyntaxHighlighter>
#include <QRegularExpression>
#include <QDebug>
#include <QPainter>
#include <QPushButton>
#include <QLabel>
#include <QLineEdit>
#include <QDoubleValidator>
#include <QColorDialog>
#include <QGraphicsSceneMouseEvent>
#include <QGraphicsEllipseItem>
#include <QGraphicsLineItem>
#include <QInputDialog>
#include <QPen>
#include <QComboBox>
#include <QSlider>
#include <QBrush>
#include <QGraphicsScene>
#include <QGraphicsView>

#include <vector>
#include <list>
#include <Windows.h>
#endif // COMMUNAL_H
